export plugin data to injection
Soluto/stitch pull request #296
Opened 2021-03-10 22:13 UTC by yoavkarako

2021-03-10 23:43 UTC, AleF83 requested changes
Run tests with `-u` flag to update snapshots. Check that the snapshots were changed as expected

2021-03-10 23:43 UTC, AleF83 commented on services/src/modules/arguments-injection/arguments-injection.ts
> +    pluginData: context?.resourceGroup?.pluginData,
`pluginData` is a bit long.
```suggestion
    plugins: context?.resourceGroup?.pluginData,
```

2021-03-10 23:43 UTC, AleF83 commented on services/tests/e2e/basic/plugins.schema.ts
> +      pl_new_data: String! @localResolver(value: "{pluginData.foo}")
```suggestion
      pl_new_data: String! @localResolver(value: "{plugins.foo}")
```

2021-03-10 23:43 UTC, AleF83 commented on services/tests/e2e/config/plugins/transform-resource-group.js
> +    newRg.pluginData = { foo: 'bar' };
`pluginData` should be initialized to an empty object before applying plugins on resource group. So plugins will add some properties to the object rather then replace/create it.

2021-03-11 00:29 UTC, yoavkarako commented
> Run tests with `-u` flag to update snapshots. Check that the snapshots were changed as expected

Can you do that? It won't run on my machine. I'll need to set it up the wsl...

2021-03-11 07:32 UTC, AleF83 commented
I've rebased a bit the branch and squashed the commits.
Just add some documentation [here](https://github.com/Soluto/stitch/blob/master/docs/arguments_injection.md) and [here](https://github.com/Soluto/stitch/blob/master/docs/plugins.md#transformresourcegroup)

2021-03-11 10:19 UTC, AleF83 approved these changes

2021-03-11 11:48 UTC, merged