Api key auth strategy
Soluto/stitch pull request #315
Opened 2021-04-08 11:37 UTC by AleF83

2021-04-08 13:47 UTC, tomeresk requested changes

2021-04-08 13:47 UTC, tomeresk commented on services/src/modules/authentication/strategies/api-key.ts
> +  }
```suggestion
  const apiKey = (request.headers[config.header] || request.query[config.queryParam]) as string
```

2021-04-08 13:47 UTC, tomeresk commented on services/src/modules/authentication/strategies/api-key.ts
> +  }
```suggestion
  if (!apiKey) throw new Error('Unauthorized');
```

2021-04-08 13:47 UTC, tomeresk commented on services/src/modules/authentication/strategies/api-key.ts
> +  if (apiKeyConfig.enabled === false) {
```suggestion
  if (!apiKeyConfig.enabled) {
```

2021-04-08 13:47 UTC, tomeresk commented on services/src/modules/authentication/strategies/api-key.ts
> +  const anonymousPaths = config.authenticatedPaths;
I don't understand why `anonymousPaths` comes from the `authenticatedPaths` config value

2021-04-08 16:21 UTC, AleF83 commented on services/src/modules/authentication/strategies/api-key.ts
> +  if (apiKeyConfig.enabled === false) {
Replaced `enabled` with `disabled`

2021-04-11 16:33 UTC, tomeresk approved these changes

2021-04-12 06:22 UTC, merged